version: '3'
services:
  web:
    build: .
    ports:
      - "808:80"
    volumes:
      - .:/code
  postgres:
    image: "postgres:10-alpine"
    volumes:
      - ./schema.sql:docker-entrypoint-initdb.d/schema.sql
